[package]
name = "cron-within-interval"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
cron = "0.12"
lazy_static = "1.5"
rand = "0.8"
regex = "1.10"

[dev-dependencies]
simple_accumulator = "0.7.0"
